name: Update VC dashboard

on:
  schedule:
    # 6 AM Pacific (13:00 UTC)
    - cron: '0 13 * * *'
    # 3 PM Pacific (22:00 UTC)
    - cron: '0 22 * * *'
  workflow_dispatch:
    # … (keep this if you want manual runs)


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Scrape latest deals and update dashboard
        run: |
          python scrape_deals.py --output vc_deals.csv
          python update_dashboard.py --csv vc_deals.csv --html dashboard.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add vc_deals.csv dashboard.html
          git commit -m "Automated daily update" || echo "No changes to commit"
          git push
